"""add site_torrent and site_sync_cursor

Revision ID: 1108fee89a70
Revises: f58f64726079
Create Date: 2026-07-09 00:42:53.162892

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1108fee89a70'
down_revision: str | None = 'f58f64726079'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_sync_cursor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tracking_since', sa.DateTime(), nullable=False),
    sa.Column('newest_publish_time', sa.DateTime(), nullable=True),
    sa.Column('newest_torrent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_new_count', sa.Integer(), nullable=True),
    sa.Column('last_full_page', sa.Boolean(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_sync_cursor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_sync_cursor_site_id'), ['site_id'], unique=True)

    op.create_table('site_torrent',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('torrent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('size_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('uploader', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('leechers', sa.Integer(), nullable=True),
    sa.Column('snatched', sa.Integer(), nullable=True),
    sa.Column('download_volume_factor', sa.Float(), nullable=True),
    sa.Column('upload_volume_factor', sa.Float(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('free_deadline', sa.DateTime(), nullable=True),
    sa.Column('imdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('douban_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('LIST', 'RSS', 'SEARCH', 'DETAIL', name='torrentsource'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('volatile_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('detail_enriched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'torrent_id', name='uq_site_torrent_site_tid')
    )
    with op.batch_alter_table('site_torrent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_torrent_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_torrent_imdb_id'), ['imdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_torrent_is_free'), ['is_free'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_torrent_publish_time'), ['publish_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_torrent_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_torrent_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_torrent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_torrent_title'))
        batch_op.drop_index(batch_op.f('ix_site_torrent_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_torrent_publish_time'))
        batch_op.drop_index(batch_op.f('ix_site_torrent_is_free'))
        batch_op.drop_index(batch_op.f('ix_site_torrent_imdb_id'))
        batch_op.drop_index(batch_op.f('ix_site_torrent_category'))

    op.drop_table('site_torrent')
    with op.batch_alter_table('site_sync_cursor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_sync_cursor_site_id'))

    op.drop_table('site_sync_cursor')
    # ### end Alembic commands ###
