"""add cadence fields to site_sync_cursor

Revision ID: a53c51c366d8
Revises: 1108fee89a70
Create Date: 2026-07-09 01:01:19.952283

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a53c51c366d8'
down_revision: str | None = '1108fee89a70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_sync_cursor', schema=None) as batch_op:
        # server_default 让已有行也能安全补上默认间隔（900=15 分钟）；
        # 应用层写入始终显式赋值，故此默认仅用于本次 ALTER 回填。
        batch_op.add_column(sa.Column(
            'sync_interval_seconds', sa.Integer(), nullable=False, server_default='900'
        ))
        batch_op.add_column(sa.Column('next_sync_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_sync_cursor', schema=None) as batch_op:
        batch_op.drop_column('next_sync_at')
        batch_op.drop_column('sync_interval_seconds')

    # ### end Alembic commands ###
