"""add config status fields to site_credential

Revision ID: b4162f0ac46b
Revises: 41c9c2b9bbbc
Create Date: 2026-07-08 22:36:37.370158

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4162f0ac46b'
down_revision: str | None = '41c9c2b9bbbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        # server_default='PENDING'：老数据升级时新列需要默认值回填，否则
        # 已有记录会因 NOT NULL 无值而报错。存量凭据回到 PENDING 会被重新验证。
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'VERIFYING', 'ACTIVE', 'FAILED', name='configstatus'), nullable=False, server_default='PENDING'))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_site_credential_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_credential_status'))
        batch_op.drop_column('last_error')
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
