"""add app_setting table

Revision ID: f58f64726079
Revises: b77cfd61a98b
Create Date: 2026-07-08 23:14:35.413907

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f58f64726079'
down_revision: str | None = 'b77cfd61a98b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_namespace'), ['namespace'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_namespace'))

    op.drop_table('app_setting')
    # ### end Alembic commands ###
