"""init site_credential and site_cookie

Revision ID: 41c9c2b9bbbc
Revises: 
Create Date: 2026-07-08 22:18:06.378213

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41c9c2b9bbbc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_cookie',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cookies', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_cookie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_cookie_site_id'), ['site_id'], unique=True)

    op.create_table('site_credential',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_type', sa.Enum('COOKIE', 'APIKEY', 'CREDENTIAL', name='authtype'), nullable=False),
    sa.Column('cookie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_credential_site_id'), ['site_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_credential_site_id'))

    op.drop_table('site_credential')
    with op.batch_alter_table('site_cookie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_cookie_site_id'))

    op.drop_table('site_cookie')
    # ### end Alembic commands ###
