"""add last_checked_at to site_credential

Revision ID: a8545b6cd9c2
Revises: b4162f0ac46b
Create Date: 2026-07-08 22:57:29.355119

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8545b6cd9c2'
down_revision: str | None = 'b4162f0ac46b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_credential', schema=None) as batch_op:
        batch_op.drop_column('last_checked_at')

    # ### end Alembic commands ###
