"""add scheduled_task and task_run

Revision ID: b77cfd61a98b
Revises: a8545b6cd9c2
Create Date: 2026-07-08 23:13:48.355512

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b77cfd61a98b'
down_revision: str | None = 'a8545b6cd9c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.Enum('INTERVAL', 'CRON', name='triggertype'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_task_task_key'), ['task_key'], unique=True)

    op.create_table('task_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='taskrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_run_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_run_task_key'), ['task_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_run_task_key'))
        batch_op.drop_index(batch_op.f('ix_task_run_status'))
        batch_op.drop_index(batch_op.f('ix_task_run_started_at'))

    op.drop_table('task_run')
    with op.batch_alter_table('scheduled_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_task_task_key'))

    op.drop_table('scheduled_task')
    # ### end Alembic commands ###
